version: "3.4"

services:
  api:
    build: .
    volumes: 
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_NAME: "urlshortener"
      DB_HOST: "db"
      DB_USER: "user"
      DB_PASSWORD: "password"
      PORT: "3000"
  
  db:
    image: postgres
    environment:
      POSTGRES_DB: "urlshortener"
      POSTGRES_HOST: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  dbadmin:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db